name: Weekly Weather History Fetch

on:
  schedule:
    - cron: "0 0 * * 2"  # every Tuesday at 00:00 UTC
  workflow_dispatch:

jobs:
  run-history:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install requests pandas
      - name: Run weatherHistoryApi script
        run: python weatherHistoryApi.py
        env:
            WEATHER_API_KEY: ${{ secrets.e5314a3a5d5249d0aff223149252412 }}
      - name: Commit results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add precip.json || true
          git add weather_history_*.json || true
          git commit -m "Update Weather History $(date -u +"%Y-%m-%d_%H-%M-%S")" || true
          git push
